# Generated by Django 4.1.2 on 2022-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appstats", "0002_counterinstance_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gaugeinstance",
            name="value",
            field=models.FloatField(),
        ),
    ]
