# Generated by Django 4.1.2 on 2022-10-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appstats", "0003_alter_gaugeinstance_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gaugeinstance",
            old_name="guage",
            new_name="gauge",
        ),
    ]
