# Generated by Django 4.1.2 on 2022-10-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appstats", "0004_rename_guage_gaugeinstance_gauge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="appstats.app",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "app")},
            },
        ),
        migrations.AddField(
            model_name="counterinstance",
            name="version",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counters",
                to="appstats.installedversion",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gaugeinstance",
            name="version",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gauges",
                to="appstats.installedversion",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="counter",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gauge",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="counter",
            unique_together={("name", "app")},
        ),
        migrations.AlterUniqueTogether(
            name="gauge",
            unique_together={("name", "app")},
        ),
        migrations.CreateModel(
            name="EventInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributes", models.JSONField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="appstats.event",
                    ),
                ),
                (
                    "install",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="appstats.install",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="appstats.installedversion",
                    ),
                ),
            ],
        ),
    ]
