# Generated by Django 4.1.2 on 2022-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appstats", "0006_alter_counterinstance_date_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="install",
            name="model",
        ),
        migrations.AddField(
            model_name="installedversion",
            name="model",
            field=models.CharField(default="foo", max_length=255),
            preserve_default=False,
        ),
    ]
