# Generated by Django 4.1.2 on 2022-10-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appstats", "0007_remove_install_model_installedversion_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="slug",
            field=models.SlugField(default="foo"),
        ),
    ]
